---
#Available algorithms for the load balancer
routing_policies:
  - "Round Robin"
  - "Least Connections"

algorithms:
 - "Random Forest"
 - "Decision Tree"
 - "Neural Network"
 - "None"
  
#starting en ending hour of simulation
start_time: 0
end_time: 24

#size of one period
size_period: 1

#number of intervals one period should be split into (steps)
steps: 3600

#probability request will be a small request (probabiliy large request will automatically be 1 - prob_small)
prob_small: 0.8

#distribution parameters of requests
mean_small: 20
std_small: 10
mean_large: 300
std_large: 80

#maximum waiting time of a request untill it leaves the system
max_wait_small: 200
max_wait_large: 1000

#rewards and costs
cost_server: 150
cost_fail: 10
reward_small: 2
reward_large: 5

#minimum and maximum number of servers
min_servers: 0
max_servers: 10
max_processes: 10

